
#액츄에이터 설정
management:
  endpoints:
    enabled-by-default: false # 모든 endpoint 를 띄우지 않고 시작한다.
    web:
      exposure:
        include: "metrics"
  endpoint:
    metrics:
      enabled: true           # 메트릭만 활성화 시킨다.



